### ISSUE TITLE
Creation of Durable Subscriber in IBM MQ fails

### ISSUE THREAD

**Issue by arinban** [ari-ban/glassfish-genericjmsra#10]
Using IBM MQ 6.0\. Generic RA is deployed in the application server and a web
application is also deployed. The EJB in the application creates a durable
subscriber. The appropriate topic connection factory and topics are defined in
IBM MQ.

The following code throws an exception sometimes -
createDurableSubscriber(topic, "genra15")

where 'genra15' is the client id value. The same is specified while creating the
topic connection factory in IBM MQ.

The code was working fine. When it failed I decreased the length of the client
id value. It passed initially and then started failing again.

The error message is :

javax.enterprise.system.stream.err|_ThreadID=19;|com.ibm.mq.jms.BrokerCommandFailedException:
Broker
command failed: MQRCCF_SUBSCRIPTION_LOCKED Reason code 3156
at com.ibm.mq.jms.MQBrokerSubscriptionEngine.openDurableSubscription(MQB
rokerSubscriptionEngine.java:1294)
at com.ibm.mq.jms.MQMigrateSubscriptionEngine.openDurableSubscription(MQ
MigrateSubscriptionEngine.java:547)
at com.ibm.mq.jms.MQSession.createDurableSubscriber(MQSession.java:5365)
at com.ibm.mq.jms.MQSession.createDurableSubscriber(MQSession.java:5185)
at com.sun.genericra.outbound.SessionAdapter.createDurableSubscriber(Ses
sionAdapter.java:308)
at com.sun.ejte.j2ee.genericra.test15.ejb.GenericRA15Bean.receiveTextMes
sage(GenericRA15Bean.java:116)

Seems to be an IBM MQ issue -
[http://www-1.ibm.com/support/docview.wss?uid=swg21116114](http://www-1.ibm.com/support/docview.wss?uid=swg21116114)
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[current]

**Comment by arinban** [comment]
@glassfishrobot Commented 
Reported by sushmita

**Comment by arinban** [comment]
@glassfishrobot Commented 
Was assigned to binod

**Comment by arinban** [comment]
@glassfishrobot Commented 
binod said:
Note that clientID should not be used within a J2EE application. Can submitter
confirm that this issue appear, even when the clientID is configured just as a
connection pool property

**Comment by arinban** [comment]
@glassfishrobot Commented 
This issue was imported from java.net JIRA GENERICJMSRA-10

**Comment by arinban** [comment]
* **Issue Imported From:** https://github.com/javaee/glassfish-genericjmsra/issues/10
* **Original Issue Raised By:**@glassfishrobot
* **Original Issue  Assigned To:** @glassfishrobot

**Comment by arinban** [comment]
**Closing this as this issue is migrated to** https://github.com/ari-ban/test1/issues/10
