### ISSUE TITLE
Cannot use DeliveryType=Synchronous in Glassfish 3

### ISSUE THREAD

**Issue by arinban** [ari-ban/glassfish-genericjmsra#42]
If you configure GenericJMSRA to use DeliveryType=Synchronous (and leave
SupportXA to its default value of true) and deploy a MDB to use it then when the
first message is received this exception is thrown:

SEVERE: java.lang.RuntimeException: Failed to obtain handle to transaction:
java.lang.Exception: Could not find transaction manager adapter
at
com.sun.genericra.inbound.sync.SyncDeliveryHelper.getTransaction(SyncDeliveryHelper.java:379)
at
com.sun.genericra.inbound.sync.SyncDeliveryHelper.runOnceStdXA(SyncDeliveryHelper.java:260)
at
com.sun.genericra.inbound.sync.SyncDeliveryHelper.deliver(SyncDeliveryHelper.java:209)
at
com.sun.genericra.inbound.sync.SyncDeliveryHelper.deliver(SyncDeliveryHelper.java:194)
at com.sun.genericra.inbound.sync.SyncWorker.run(SyncWorker.java:125)
at com.sun.enterprise.connectors.work.OneWork.doWork(OneWork.java:92)
at
com.sun.corba.ee.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:492)
at
com.sun.corba.ee.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:528)
Caused by: java.lang.Exception: Could not find transaction manager adapter
at
com.sun.genericra.inbound.sync.TxMgr.getTransactionManager(TxMgr.java:221)
at
com.sun.genericra.inbound.sync.SyncDeliveryHelper.getTransaction(SyncDeliveryHelper.java:376)
... 7 more
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[current]

**Comment by arinban** [comment]
@glassfishrobot Commented 
Reported by nigeldeakin

**Comment by arinban** [comment]
@glassfishrobot Commented 
Was assigned to sats

**Comment by arinban** [comment]
@glassfishrobot Commented 
nigeldeakin said:
The cause of this bug is that the JNDI location where the TransactionManager can
be found has changed. In Glassfish 2 it is "java:comp/UserTransaction" whereas
in Glassfish 3 it is "java:appserver/TransactionManager". The TxMgr class has
been extended to try both in turn.

**Comment by arinban** [comment]
@glassfishrobot Commented 
nigeldeakin said:
Fixed in 2.1a

**Comment by arinban** [comment]
@glassfishrobot Commented 
Marked as **fixed** on Wednesday, September 15th 2010, 2:14:41 am

**Comment by arinban** [comment]
@glassfishrobot Commented 
This issue was imported from java.net JIRA GENERICJMSRA-42

**Comment by arinban** [comment]
* **Issue Imported From:** https://github.com/javaee/glassfish-genericjmsra/issues/42
* **Original Issue Raised By:**@glassfishrobot
* **Original Issue  Assigned To:** @glassfishrobot
* **Original Issue  Closed By:**@glassfishrobot
